name: Render README

on:
  push:
   branches: 
    - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate
        run: |
          ./generate.sh

          # Skip if no changes.
          if [[ ! "$(git status --porcelain)" ]]; then
            echo "No changes."
            exit 0
          fi

          # Push code.
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Re-generate README"
          git push